name = "Bliss"
license = "GPLv3"
licenselink = "https://www.gnu.org/licenses/gpl-3.0.txt"
description = "Lightweight Hugo theme with a focus on content"
homepage = "https://github.com/afonsorib/bliss"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = "Afonso Ribeiro"
  homepage = "https://afonsorib.github.io"
